### ISSUE TITLE
if required, perform initialization 

### ISSUE THREAD

**Issue by docktermj** [Senzing/aws-cloudformation-ecs-senzing-stack-choices#20]
Currently https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-basic performs one-time initialization required for the `aws-cloudformation-ecs-senzing-stack-choices` stack to run properly

1. https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-basic/blob/eb91cd707746fae8099211b64c2a5451e7e8e507/cloudformation.yaml#L2351-L2444
1. https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-basic/blob/eb91cd707746fae8099211b64c2a5451e7e8e507/cloudformation.yaml#L3351-L3543

This issue is to check to see if initialization has already been performed.  If it hasn't, then perform initialization.

**Comment by roncewind** [comment]
Choices now also performs the initialization.
