### ISSUE TITLE
Stack fails when deploying only non web services

### ISSUE THREAD

**Issue by ssasidharanwp** [Senzing/aws-cloudformation-ecs-senzing-stack-choices#62]
**Describe the bug**
Deploying this template fails when no web instances are present. When using sshd, redoer and stream loader the deployment fails at task `LambdaRunnerInitEfs`

with this error
```
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the RunTask operation: User: arn:aws:sts::REDACTED:assumed-role/senzing-temp-choices-IamRoleLambda-1KMQ1R2KS5BYO/senzing-temp-choices-lambda-run-task-and-wait is not authorized to perform: iam:PassRole on resource: arn:aws:iam::REDACTED:role/senzing-temp-choices-IamRoleInitEfs-XLGSXNEJ3OZ4 because no identity-based policy allows the iam:PassRole action
```
**To Reproduce**
1. Load the latest github cloudformation.yaml into AWS 
2. Input required params
3. Select only sshd, stream-loader and redoer services to be deployed to ecs cluster
4. The stack fails and then rollback happens

**Expected behavior**
The cloudformation should work even with only the above 3 services or even with only the sshd service

**Additional context**
This happens due to  `IamPolicyPassRole` role being dependent on any of the web services enabled(https://github.com/Senzing/aws-cloudformation-ecs-senzing-stack-choices/blob/main/cloudformation.yaml#L1068) but the efs init requires this role and efs init is probably required irrespective of the services deployed i think

**Comment by roncewind** [comment]
PR merged, release created, moved to S3
